# Generated by Django 3.2 on 2021-04-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_alter_turf_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='turf',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
