# Generated by Django 3.2 on 2021-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_turf_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_facility',
            name='f1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='turf_facility',
            name='f8',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
