# Generated by Django 3.2 on 2021-05-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_auto_20210422_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_type', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket')], max_length=100)),
                ('day', models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend'), ('Holiday', 'Holiday')], max_length=100)),
                ('timing', models.CharField(choices=[('00:00-06:00', '00:00-06:00'), ('00:00-10:00', '00:00-10:00'), ('00:00-02:00', '00:00-02:00'), ('00:00-05:00', '00:00-05:00'), ('00:00-01:00', '00:00-01:00'), ('06:00-10:00', '06:00-10:00'), ('06:00-12:00', '06:00-12:00'), ('06:00-18:00', '06:00-18:00'), ('06:00-17:00', '06:00-17:00'), ('02:00-06:00', '02:00-06:00'), ('10:00-16:00', '10:00-16:00'), ('12:00-16:00', '12:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('17:00-18:00', '17:00-18:00'), ('18:00-23:59', '18:00-23:59'), ('05:00-09:00', '05:00-09:00'), ('09:00-17:00', '09:00-17:00'), ('05:00-16:00', '05:00-16:00'), ('05:00-18:00', '05:00-18:00'), ('05:00-10:00', '05:00-10:00'), ('10:00-16:00', '10:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('16:00-23:59', '16:00-23:59'), ('18:00-19:00', '18:00-19:00'), ('19:00-23:59', '19:00-23:59'), ('18:00-23:59', '18:00-23:59'), ('00:00-23:59', '00:00-23:59')], max_length=100)),
                ('price', models.CharField(choices=[('1200/hour', '1200/hour'), ('1000/hour', '1000/hour'), ('1300/hour', '1300/hour'), ('1500/hour', '1500/hour'), ('1800/hour', '1800/hour'), ('800/hour', '800/hour'), ('900/hour', '900/hour'), ('700/hour', '700/hour'), ('3000/hour', '3000/hour'), ('2000/hour', '2000/hour'), ('3600/hour', '3600/hour'), ('1100/hour', '1100/hour'), ('1400/hour', '1400/hour'), ('1700/hour', '1700/hour'), ('400/hour', '400/hour'), ('500/hour', '500/hour')], max_length=100)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turf.turf')),
            ],
        ),
    ]
