# Generated by Django 3.2 on 2021-05-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0012_pricing_chart_timing2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_chart',
            name='timing2',
        ),
    ]
