# Generated by Django 3.2 on 2021-06-26 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turf', '0014_alter_pricing_chart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_slot3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('s_time', models.CharField(max_length=100)),
                ('e_time', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('s_type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
