# Generated by Django 3.2 on 2021-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0015_booking_slot3'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_name', models.CharField(max_length=100)),
                ('t2_name', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('s_time', models.CharField(max_length=50)),
                ('e_time', models.CharField(max_length=50)),
                ('turf_name', models.CharField(max_length=100)),
                ('no_pl', models.IntegerField(default=5)),
            ],
        ),
    ]
